### ISSUE TITLE
I'm unable to change the currency

### ISSUE THREAD

**Issue by Fayaz139** [hisabi-app/hisabi#79]
i tried watching your video but couldn't change the currency

**Comment by saleem-hadad** [comment]
did change that in the hisabi.php file?

**Comment by Fayaz139** [comment]
I tried to change it on hisabi.php file but it shows me this error: “php "/Users/sfayaz/hisabi/config/hisabi.php"
sfayaz@Fayazs-MacBook-Air hisabi % php "/Users/sfayaz/hisabi/config/hisabi.php"
PHP Fatal error:  Uncaught Error: Class "App\Domain\SectionDivider" not found in /Users/sfayaz/hisabi/config/hisabi.php:43
Stack trace:
#0 {main}
  thrown in /Users/sfayaz/hisabi/config/hisabi.php on line 43

Fatal error: Uncaught Error: Class "App\Domain\SectionDivider" not found in /Users/sfayaz/hisabi/config/hisabi.php:43
Stack trace:
#0 {main}
  thrown in /Users/sfayaz/hisabi/config/hisabi.php on line 43”

**Comment by saleem-hadad** [comment]
can you please share a screenshot of the config?
